import type { Metadata } from "next"
import { ReactNode } from "react"
import "./globals.css"
import { inter } from "@/fonts/font"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="es">
      <head>
        <title>Card Details</title>
      </head>

      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  )
}
